tag: md-sdk-std-cfg
version: 0.0.1 
md: classic # null
base:
  text_color: 
  background_color: 
  title_bar_thikness: 
  title_bar_color: 
  

custom: 
  enabled: true
  mode: add # replace
  colors: 
    enabled: true
    begining_tag: ~~
    ending_tag: ~~
    unit_config: 
      - color: 
          name: red
          tag: r
          hex_code: 